spring.application.name=UserService
twilio.accountSid=AC5ef4e7e9cc6aefb755538c8934910e69
twilio.authToken=edbabb25a25e6c9f419141e1a25cccc9
twilio.phoneNumber=+15047882765
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/employeedb
spring.datasource.username=root
spring.datasource.password=Avinash@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.boot.admin.client.url=http://localhost:1111/
management.endpoints.web.exposure.include=health,info